In [43]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

In [44]:
titanic_train=pd.read_csv('C:\\Users\\hemanth kumar\\Desktop\\kaggle project\\titanic\\train.csv')
titanic_test=pd.read_csv('C:\\Users\\hemanth kumar\\Desktop\\kaggle project\\titanic\\test.csv')

In [45]:
print(titanic_train.info())
print('-'*40)
print(titanic_test.info()) 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Pass

## training set incomplete data: Age,Cabin,embarked age and cabin are worse

In [46]:
titanic_train['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

## better to drop cabin

In [47]:
titanic_train=titanic_train.drop('Cabin',axis=1)

In [48]:
titanic_train['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [49]:
titanic_train['Embarked'].mode() 

0    S
dtype: object

In [50]:
titanic_train['Embarked']=titanic_train['Embarked'].replace(np.nan,'S') 

In [51]:
titanic_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    object 
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB


## age is important feature but very less data

In [52]:
titanic_train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

## droping the unknown data

In [53]:
titanic_train=titanic_train.dropna()

In [54]:
titanic_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 714 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  714 non-null    int64  
 1   Survived     714 non-null    int64  
 2   Pclass       714 non-null    int64  
 3   Name         714 non-null    object 
 4   Sex          714 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        714 non-null    int64  
 7   Parch        714 non-null    int64  
 8   Ticket       714 non-null    object 
 9   Fare         714 non-null    float64
 10  Embarked     714 non-null    object 
dtypes: float64(2), int64(5), object(4)
memory usage: 66.9+ KB


In [55]:
titanic_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [56]:
titanic_test['Age'].mean()

30.272590361445783

In [57]:
titanic_test['Fare'].mean()

35.6271884892086

In [58]:
titanic_test['Age']=titanic_test['Age'].replace(np.nan,30)
titanic_test['Fare']=titanic_test['Fare'].replace(np.nan,35.63)

In [59]:
titanic_test=titanic_test.drop('Cabin',axis=1)

In [60]:
titanic_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          418 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         418 non-null    float64
 9   Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(4)
memory usage: 32.8+ KB


In [61]:
y_train=titanic_train['Survived']
titanic_train=titanic_train.drop('Survived',axis=1)

In [62]:
titanic_train=titanic_train.drop(['PassengerId','Name','Ticket'],axis=1)
titanic_test=titanic_test.drop(['PassengerId','Name','Ticket'],axis=1)

In [63]:
c=list(titanic_test.columns)
c 

['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']

In [65]:
p1=titanic_train.values
p2=titanic_test.values
x=np.vstack((p1,p2))
X=pd.DataFrame(x,columns=c)
len(x) 

1132

In [68]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
le=LabelEncoder()
x[:,1]=le.fit_transform(x[:,1])

from sklearn.compose import ColumnTransformer
ct=ColumnTransformer(transformers=[('ohe',OneHotEncoder(),[-1])],remainder='passthrough')

x=ct.fit_transform(x) 
x=x[:,1:]  ## to avoid the dummy variable trap

x[1,:]

array([0.0, 0.0, 1, 0, 38.0, 1, 0, 71.2833], dtype=object)

In [69]:
from sklearn.preprocessing import StandardScaler
ss_x=StandardScaler()
x=ss_x.fit_transform(x)

In [70]:
len(titanic_train) 

714

In [71]:
x_train=x[0:714,:]
x_test=x[714:,:]

In [72]:
import keras
from keras import Sequential
from keras.layers import Dense

In [73]:
classifier=Sequential([Dense(4, input_shape=(8,),init='uniform',activation='relu'),
                      Dense(4,init='uniform',activation='relu'),
                      Dense(4,init='uniform',activation='relu'),
                      Dense(1,init='uniform',activation='relu')])

C:\Users\hemanth kumar\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(4, input_shape=(8,), activation="relu", kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.
C:\Users\hemanth kumar\anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(4, activation="relu", kernel_initializer="uniform")`
  
C:\Users\hemanth kumar\anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(4, activation="relu", kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\hemanth kumar\anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="relu", kernel_initializer="uniform")`
  after removing the cwd from sys.path.


In [74]:
classifier.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 4)                 36        
_________________________________________________________________
dense_6 (Dense)              (None, 4)                 20        
_________________________________________________________________
dense_7 (Dense)              (None, 4)                 20        
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 5         
Total params: 81
Trainable params: 81
Non-trainable params: 0
_________________________________________________________________


In [75]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [76]:
classifier.fit(x_train,y_train,batch_size=5,epochs=30)

Epoch 1/30
714/714 [==============================] - 1s 894us/step - loss: 6.5466 - accuracy: 0.5938
Epoch 2/30
714/714 [==============================] - 0s 312us/step - loss: 6.5466 - accuracy: 0.5938
Epoch 3/30
714/714 [==============================] - 0s 272us/step - loss: 6.5466 - accuracy: 0.5938
Epoch 4/30
714/714 [==============================] - 0s 270us/step - loss: 6.5466 - accuracy: 0.5938
Epoch 5/30
714/714 [==============================] - 0s 271us/step - loss: 6.5466 - accuracy: 0.5938
Epoch 6/30
714/714 [==============================] - 0s 277us/step - loss: 6.5466 - accuracy: 0.5938
Epoch 7/30
714/714 [==============================] - 0s 264us/step - loss: 6.5466 - accuracy: 0.5938
Epoch 8/30
714/714 [==============================] - 0s 313us/step - loss: 6.5466 - accuracy: 0.5938
Epoch 9/30
714/714 [==============================] - 0s 296us/step - loss: 6.5466 - accuracy: 0.5938
Epoch 10/30
714/714 [==============================] - 0s 279us/step - loss: 6.546

In [77]:
len(y_pred)  

384

In [78]:
y_pred=classifier.predict(x_test)
y_pred=(y_pred>0.5)

In [79]:
y_pred=classifier.predict(x_test)
y_pred=(y_pred>0.5)

y_test=pd.read_csv('C:\\Users\\hemanth kumar\\Desktop\\gender_submission (4).csv')
y_test.head()

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test.iloc[:,1],y_pred)
cm 

array([[266,   0],
       [152,   0]], dtype=int64)

In [80]:
y_pred

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [