In [47]:
import numpy as np
import pandas as pd
import math

In [48]:
titanic_train=pd.read_csv('C:\\Users\\hemanth kumar\\Desktop\\kaggle project\\titanic\\train.csv')
titanic_test=pd.read_csv('C:\\Users\\hemanth kumar\\Desktop\\kaggle project\\titanic\\test.csv')

In [49]:
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [50]:
titanic_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [51]:
x=titanic_train.copy()
y=titanic_train['Survived']
y.columns=[0]
x_t=titanic_test.copy()
x_t.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [52]:
y=pd.DataFrame(y)

# trail 1
## considering only these features

In [53]:
x=x.drop(['PassengerId','Survived','Name','Ticket','Cabin'],axis=1)
x_t=x_t.drop(['PassengerId','Name','Ticket','Cabin'],axis=1)
x_t.head()

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  34.5      0      0   7.8292        Q
1       3  female  47.0      1      0   7.0000        S
2       2    male  62.0      0      0   9.6875        Q
3       3    male  27.0      0      0   8.6625        S
4       3  female  22.0      1      1  12.2875        S

In [54]:
x_t.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    418 non-null    int64  
 1   Sex       418 non-null    object 
 2   Age       332 non-null    float64
 3   SibSp     418 non-null    int64  
 4   Parch     418 non-null    int64  
 5   Fare      417 non-null    float64
 6   Embarked  418 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 23.0+ KB


In [55]:
ones=np.ones((891,1))
ones=pd.DataFrame(data=ones,columns=['ones'])
x=pd.merge(ones,x,left_index=True,right_index=True) #creating bias column of ones.

In [56]:
ones_t=np.ones((418,1))
ones_t=pd.DataFrame(data=ones_t,columns=['ones_t'])
x_t=pd.merge(ones_t,x_t,left_index=True,right_index=True) #creating bias column of ones.

In [57]:
x['Sex']=x['Sex'].replace(['male','female'],[1,0])
x['Embarked']=x['Embarked'].replace(['C','Q','S'],[1,2,3])
x['Embarked']=x['Embarked'].replace(np.NaN,2)
mean_age=round(np.mean(x['Age']))
x['Age']=x['Age'].replace(np.NaN,mean_age)
m=len(x)

x_t['Sex']=x_t['Sex'].replace(['male','female'],[1,0])
x_t['Embarked']=x_t['Embarked'].replace(['C','Q','S'],[1,2,3])
x_t['Embarked']=x_t['Embarked'].replace(np.NaN,2)
mean_age=round(np.mean(x_t['Age']))
x_t['Age']=x_t['Age'].replace(np.NaN,mean_age)
m_t=len(x_t)

In [58]:
a=pd.DataFrame(data=x_t.loc[:,('Pclass','Fare')])
b=a.groupby('Pclass').mean()
b

Fare
Pclass           
1       94.280297
2       22.202104
3       12.459678

In [59]:
lib1={}
l=[]
l1=list(b.index)
l2=list(b.Fare)
for i in range(len(b)):
    l.append((l1[i],l2[i]))
lib1.update(l)
lib1

{1: 94.28029719626169, 2: 22.20210430107527, 3: 12.459677880184334}

c=pd.DataFrame(data=x_t.loc[:,('Pclass','Fare')])
c=c.set_index('Pclass')
for i in range(1,4):
    c.loc[i,'Fare']=c.loc[i,'Fare'].replace(np.NaN,lib1.get(i))
d=list(c['Fare'])
d=pd.Series(d)
x_t=x_t.drop(['Fare'],axis=1)
x_t['fare']=d
x_t.isnull().values.any()

In [60]:
x_t['Fare']=x_t['Fare'].replace(np.NaN,lib1.get(3))

In [61]:
x_t.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   ones_t    418 non-null    float64
 1   Pclass    418 non-null    int64  
 2   Sex       418 non-null    int64  
 3   Age       418 non-null    float64
 4   SibSp     418 non-null    int64  
 5   Parch     418 non-null    int64  
 6   Fare      418 non-null    float64
 7   Embarked  418 non-null    int64  
dtypes: float64(3), int64(5)
memory usage: 26.2 KB


In [62]:
x_t.head()

ones_t  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0     1.0       3    1  34.5      0      0   7.8292         2
1     1.0       3    0  47.0      1      0   7.0000         3
2     1.0       2    1  62.0      0      0   9.6875         2
3     1.0       3    1  27.0      0      0   8.6625         3
4     1.0       3    0  22.0      1      1  12.2875         3

In [63]:
#lib1={c['Pclass']:c['Fare']

In [64]:
#x_t.isnull().values.any()
x_t.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   ones_t    418 non-null    float64
 1   Pclass    418 non-null    int64  
 2   Sex       418 non-null    int64  
 3   Age       418 non-null    float64
 4   SibSp     418 non-null    int64  
 5   Parch     418 non-null    int64  
 6   Fare      418 non-null    float64
 7   Embarked  418 non-null    int64  
dtypes: float64(3), int64(5)
memory usage: 26.2 KB


In [65]:
x_t['Fare'].isnull().values.any()

False

In [25]:
pd.DataFrame.isnull?

## initializing random theta values

In [13]:
theta=np.random.randn(8)
theta=pd.DataFrame(theta,index=x.columns)
n=len(theta)
theta

0
ones      1.429005
Pclass    0.508515
Sex       0.613530
Age       0.310711
SibSp    -0.716715
Parch     0.280649
Fare     -0.771486
Embarked -0.440178

In [12]:
h_theta=np.dot(x,theta)
h_theta=pd.DataFrame(h_theta)
h_theta=round(1/(1+np.exp(-h_theta)))
h_theta.head()

0
0  1.0
1  1.0
2  1.0
3  1.0
4  1.0

## applying BFGS

In [13]:
from scipy.optimize import minimize

In [14]:
def mul(a,b):
    return np.dot(a,b)

In [15]:
def j_theta(theta1):
    theta1=pd.DataFrame(theta1,index=x.columns)
    h_theta1=np.dot(x,theta1)
    h_theta1=pd.DataFrame(h_theta1)
    h_theta1=1/(1+np.exp(-h_theta1))
    m=len(x)
    b=(-1/m)*(mul(y.T,np.log(h_theta1))+mul((1-y).T,np.log(1-h_theta1)))
    return b


In [16]:
result=minimize(j_theta,theta,method='BFGS')

C:\Users\hemanth kumar\anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in log
  import sys


In [17]:
print(result)

      fun: array([[nan]])
 hess_inv: array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])
      jac: array([nan, nan, nan, nan, nan, nan, nan, nan])
  message: 'NaN result encountered.'
     nfev: 10
      nit: 0
     njev: 1
   status: 3
  success: False
        x: array([ 1.80815697,  0.3415429 ,  0.12834403, -0.08606258, -0.91414877,
        0.74037533,  0.12903538, -0.29771981])


In [18]:
print(result.x)

[ 1.80815697  0.3415429   0.12834403 -0.08606258 -0.91414877  0.74037533
  0.12903538 -0.29771981]


In [19]:
opt_theta=pd.DataFrame(result.x,index=x.columns)

In [20]:
opt_theta

0
ones      1.808157
Pclass    0.341543
Sex       0.128344
Age      -0.086063
SibSp    -0.914149
Parch     0.740375
Fare      0.129035
Embarked -0.297720

In [21]:
j_theta(theta)

C:\Users\hemanth kumar\anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in log
  import sys


array([[nan]])

In [22]:
j_theta(opt_theta)

C:\Users\hemanth kumar\anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in log
  import sys


array([[nan]])

In [23]:
x.isnull().values.any()

False

In [24]:
x1=x[0:5]
y1=y[0:5]
h=np.dot(x1,opt_theta)
h=pd.DataFrame(h)
h=1/(1+np.exp(-h))
y1=np.array(y1)
h=np.array(h)
l=(np.dot(y1.T,(np.log(h)))+np.dot((1-y1).T,(np.log(1-h))))/5
l

array([[-0.38974399]])

In [25]:
j_theta(theta)

C:\Users\hemanth kumar\anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in log
  import sys


array([[nan]])

## using gradient descent

In [26]:
def h_theta1(tet):
    a=np.dot(x,tet)
    a=1/(1+np.exp(-a))
    a=pd.DataFrame(a,columns=['Survived'])
    return a
def grad_descent(theta1,a):   # a for alpha
    for j in range(n):
        theta1.iloc[j]=theta1.iloc[j]-a*(np.dot((h_theta1(theta1)-y).T,x.iloc[:,j]))
    return theta1

In [37]:
g1=grad_descent(theta,0.2)

C:\Users\hemanth kumar\anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until


In [28]:
h_theta1(theta)-y

C:\Users\hemanth kumar\anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until


Survived
0         0.0
1         0.0
2        -1.0
3         0.0
4         0.0
..        ...
886       0.0
887       0.0
888       1.0
889       0.0
890       0.0

[891 rows x 1 columns]

In [45]:
np.round(np.dot(x,g1))

array([[-2.72910e+04],
       [ 3.66900e+03],
       [-3.27840e+04],
       [-7.45000e+03],
       [-4.68490e+04],
       [-3.87880e+04],
       [-3.82910e+04],
       [ 1.60340e+04],
       [-3.15490e+04],
       [ 5.02700e+03],
       [ 9.26800e+03],
       [-6.67550e+04],
       [-2.34050e+04],
       [-3.27510e+04],
       [-1.40920e+04],
       [-7.11790e+04],
       [ 2.29650e+04],
       [-3.48600e+04],
       [-3.17690e+04],
       [-3.98800e+04],
       [-3.12110e+04],
       [-4.11120e+04],
       [-1.56140e+04],
       [-1.20840e+04],
       [ 6.76500e+03],
       [-3.09800e+04],
       [-3.99890e+04],
       [ 2.02404e+05],
       [-3.91900e+04],
       [-3.91700e+04],
       [-3.79260e+04],
       [ 8.25190e+04],
       [-3.93040e+04],
       [-9.33290e+04],
       [ 2.87900e+04],
       [-1.94690e+04],
       [-3.99850e+04],
       [-2.49680e+04],
       [-1.15060e+04],
       [-1.13860e+04],
       [-5.33530e+04],
       [-2.30630e+04],
       [-3.93970e+04],
       [ 3.

## using logistic regresion model(from scikit)

In [66]:
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [67]:
model=LogisticRegression(C=1E6)
model=model.fit(x,y)

C:\Users\hemanth kumar\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [69]:
prediction=model.predict(x_t)

In [71]:
result=pd.DataFrame(data=prediction,index=titanic_test.PassengerId)
result.head()

0
PassengerId   
892          0
893          0
894          0
895          0
896          1