In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

titanic_train=pd.read_csv('C:\\Users\\hemanth kumar\\Desktop\\kaggle project\\titanic\\train.csv')
titanic_test=pd.read_csv('C:\\Users\\hemanth kumar\\Desktop\\kaggle project\\titanic\\test.csv')

y_train=titanic_train.iloc[:,1].values

titanic_train=titanic_train.drop(['PassengerId','Survived','Name','Ticket','Cabin'],axis=1)
titanic_test=titanic_test.drop(['PassengerId','Name','Ticket','Cabin'],axis=1)


x_train=titanic_train.iloc[:,:].values
x_test=titanic_test.iloc[:,:].values

x=np.vstack((x_train,x_test))

X=pd.DataFrame(x,columns=['Pclass', 'Sex', 'Age', 'SibSp','Parch','Fare', 'Embarked'])

X['Embarked'].fillna(value='S',inplace=True)
X['Age'].fillna(value=X['Age'].mean(),inplace=True)
X['Fare'].fillna(value=X['Fare'].mean(),inplace=True)


In [2]:
X.head(10)

Pclass     Sex        Age SibSp Parch     Fare Embarked
0      3    male  22.000000     1     0   7.2500        S
1      1  female  38.000000     1     0  71.2833        C
2      3  female  26.000000     0     0   7.9250        S
3      1  female  35.000000     1     0  53.1000        S
4      3    male  35.000000     0     0   8.0500        S
5      3    male  29.881138     0     0   8.4583        Q
6      1    male  54.000000     0     0  51.8625        S
7      3    male   2.000000     3     1  21.0750        S
8      3  female  27.000000     0     2  11.1333        S
9      2  female  14.000000     1     0  30.0708        C

In [3]:
X.isnull().values.any()

False

In [4]:
X=X.iloc[:,:].values
X[1,:]

array([1, 'female', 38.0, 1, 0, 71.2833, 'C'], dtype=object)

In [5]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
le=LabelEncoder()
X[:,1]=le.fit_transform(X[:,1])

from sklearn.compose import ColumnTransformer
ct=ColumnTransformer(transformers=[('ohe',OneHotEncoder(),[-1])],remainder='passthrough')

X=ct.fit_transform(X)

In [6]:
X=X[:,1:]

In [7]:
X[1,:]

array([0.0, 0.0, 1, 0, 38.0, 1, 0, 71.2833], dtype=object)

In [8]:
X=pd.DataFrame(X,columns=['e1','e2','Pclass','Sex','Age','SibSp','Parch','Fare'])
X.head()

e1 e2 Pclass Sex Age SibSp Parch     Fare
0  0  1      3   1  22     1     0     7.25
1  0  0      1   0  38     1     0  71.2833
2  0  1      3   0  26     0     0    7.925
3  0  1      1   0  35     1     0     53.1
4  0  1      3   1  35     0     0     8.05

In [9]:
from sklearn.preprocessing import StandardScaler
ss_x=StandardScaler()
X=ss_x.fit_transform(X)
# now x_train and x_test are arrays

In [10]:
x_train=X[0:891,:]
x_test=X[891:,:]

In [11]:
x_train[1,:]

array([-0.32204029, -1.52669211, -1.54609786, -1.34499549,  0.63043107,
        0.48128777, -0.4449995 ,  0.73450256])

## neural network

In [12]:
import keras 
from keras import Sequential
from keras.layers import Dense

classifier = Sequential([Dense(input_dim=8,output_dim=5,init='uniform',activation='relu'),
                        Dense(output_dim=5,init='uniform',activation='relu'),
                        Dense(output_dim=5,init='uniform',activation='relu'),
                        Dense(output_dim=1,init='uniform',activation='sigmoid')])

Using TensorFlow backend.
C:\Users\hemanth kumar\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\hemanth kumar\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\hemanth kumar\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\hemanth kumar\anaconda3\lib\site-packages\tenso

Instructions for updating:
Colocations handled automatically by placer.


C:\Users\hemanth kumar\anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=8, activation="relu", units=5, kernel_initializer="uniform")`
  """
C:\Users\hemanth kumar\anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=5, kernel_initializer="uniform")`
  
C:\Users\hemanth kumar\anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=5, kernel_initializer="uniform")`
  import sys
C:\Users\hemanth kumar\anaconda3\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [13]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [14]:
classifier.fit(x_train,y_train,batch_size=5,epochs=30)

Instructions for updating:
Use tf.cast instead.
Epoch 1/30
891/891 [==============================] - 1s 658us/step - loss: 0.6806 - accuracy: 0.6162
Epoch 2/30
891/891 [==============================] - 0s 271us/step - loss: 0.5684 - accuracy: 0.6162
Epoch 3/30
891/891 [==============================] - 0s 268us/step - loss: 0.5364 - accuracy: 0.7059
Epoch 4/30
891/891 [==============================] - 0s 267us/step - loss: 0.5240 - accuracy: 0.8081
Epoch 5/30
891/891 [==============================] - 0s 262us/step - loss: 0.5160 - accuracy: 0.8193
Epoch 6/30
891/891 [==============================] - 0s 260us/step - loss: 0.5073 - accuracy: 0.8182
Epoch 7/30
891/891 [==============================] - 0s 264us/step - loss: 0.5000 - accuracy: 0.8249
Epoch 8/30
891/891 [==============================] - 0s 267us/step - loss: 0.4949 - accuracy: 0.8159
Epoch 9/30
891/891 [==============================] - 0s 264us/step - loss: 0.4891 - accuracy: 0.8114
Epoch 10/30
891/891 [=============

In [20]:
y_pred=classifier.predict(x_test)
y_pred=(y_pred>0.5)

y_test=pd.read_csv('C:\\Users\\hemanth kumar\\Desktop\\gender_submission (4).csv')
y_test.head()

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test.iloc[:,1],y_pred)
cm

array([[251,  15],
       [ 19, 133]], dtype=int64)

In [22]:
test_id=titanic_test.iloc[:,0]

In [35]:
output = pd.DataFrame({'PassengerId': test_id.values, 'Survived': y_pred})
output.head()

PassengerId Survived
0            3  [False]
1            3  [False]
2            2  [False]
3            3  [False]
4            3  [False]

In [26]:
 test_id.values

array([3, 3, 2, 3, 3, 3, 3, 2, 3, 3, 3, 1, 1, 2, 1, 2, 2, 3, 3, 3, 1, 3,
       1, 1, 1, 3, 1, 3, 1, 3, 2, 2, 3, 3, 1, 3, 3, 3, 3, 3, 3, 1, 3, 2,
       1, 3, 1, 3, 1, 3, 1, 2, 2, 1, 2, 3, 3, 3, 3, 1, 3, 2, 3, 3, 1, 2,
       3, 1, 1, 1, 3, 3, 3, 1, 1, 1, 3, 1, 2, 3, 3, 1, 1, 3, 2, 3, 3, 3,
       3, 2, 3, 3, 1, 3, 1, 3, 1, 3, 3, 3, 1, 2, 3, 3, 3, 3, 3, 3, 3, 2,
       2, 3, 1, 3, 1, 3, 3, 3, 1, 2, 2, 3, 1, 3, 3, 3, 3, 3, 2, 3, 3, 1,
       3, 3, 3, 3, 3, 2, 3, 3, 3, 1, 1, 2, 1, 3, 1, 3, 1, 2, 1, 3, 3, 3,
       3, 3, 1, 3, 1, 3, 3, 3, 2, 3, 2, 3, 1, 3, 1, 3, 3, 3, 3, 3, 3, 2,
       2, 1, 2, 1, 2, 1, 1, 3, 1, 2, 2, 3, 3, 2, 2, 1, 3, 2, 2, 3, 1, 3,
       2, 3, 3, 3, 1, 2, 2, 1, 3, 2, 1, 3, 3, 3, 2, 2, 3, 1, 3, 1, 1, 3,
       2, 3, 2, 3, 1, 3, 3, 3, 3, 2, 2, 1, 3, 3, 1, 3, 1, 3, 2, 1, 1, 2,
       1, 3, 3, 1, 2, 2, 2, 3, 2, 3, 1, 3, 3, 3, 3, 3, 2, 3, 3, 3, 2, 3,
       2, 3, 1, 3, 3, 3, 1, 3, 1, 3, 3, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
       3, 1, 3, 3, 1, 3, 3, 1, 3, 3, 2, 3, 1, 3, 3,

In [32]:
y_pred=y_pred.reshape(418,1)

In [34]:
y_pred=y_pred.tolist()
y_pred

[[False],
 [False],
 [False],
 [False],
 [False],
 [False],
 [True],
 [False],
 [True],
 [False],
 [False],
 [False],
 [True],
 [False],
 [True],
 [True],
 [False],
 [False],
 [False],
 [False],
 [False],
 [False],
 [True],
 [True],
 [True],
 [False],
 [True],
 [False],
 [False],
 [False],
 [False],
 [False],
 [False],
 [False],
 [True],
 [False],
 [True],
 [True],
 [False],
 [False],
 [False],
 [False],
 [False],
 [True],
 [True],
 [False],
 [False],
 [False],
 [True],
 [False],
 [True],
 [False],
 [True],
 [True],
 [False],
 [False],
 [False],
 [False],
 [False],
 [True],
 [False],
 [False],
 [False],
 [True],
 [True],
 [True],
 [True],
 [False],
 [False],
 [True],
 [True],
 [False],
 [True],
 [True],
 [True],
 [False],
 [False],
 [True],
 [False],
 [True],
 [False],
 [False],
 [False],
 [False],
 [False],
 [False],
 [True],
 [True],
 [True],
 [True],
 [False],
 [False],
 [True],
 [False],
 [True],
 [False],
 [True],
 [False],
 [True],
 [False],
 [True],
 [False],
 [False],
 [False],

In [36]:
True==1

True